parameters:
- name: osxRuntime
  type: string
  default: osx-x64

steps:
  - task: DownloadPipelineArtifact@1
    displayName: Download signed payload
    inputs:
      buildType: 'current'
      artifactName: 'tmp.${{ parameters.osxRuntime }}.payload_signed'
      downloadPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/payload'

  - task: UseDotNet@2
    displayName: Use .NET SDK 6.0.201
    inputs:
      packageType: sdk
      version: 6.0.201

  - script: dotnet tool install --global nbgv
    displayName: Install Nerdbank.GitVersioning tool

  - script: nbgv cloud --common-vars
    displayName: Set version variables

  - script: src/osx/Installer.Mac/pack.sh --payload='$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/payload' --version='$(GitBuildVersionSimple)' --output='$(Build.StagingDirectory)/components/com.microsoft.gitcredentialmanager.component.pkg'
    displayName: Create component package

  - script: src/osx/Installer.Mac/dist.sh --package-path='$(Build.StagingDirectory)/components' --version='$(GitBuildVersionSimple)' --output='$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/pkg/gcmcore-osx-$(GitBuildVersionSimple).pkg' --runtime=${{ parameters.osxRuntime }} || exit 1
    displayName: Create product archive

  - task: PublishPipelineArtifact@0
    displayName: Upload unsigned package
    inputs:
      artifactName: 'tmp.${{ parameters.osxRuntime }}.installer_unsigned'
      targetPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/pkg/gcmcore-osx-$(GitBuildVersionSimple).pkg'
