parameters:
- name: osxRuntime
  type: string
  default: osx-x64

steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK 6.0.201
    inputs:
      packageType: sdk
      version: 6.0.201

  - script: src/osx/Installer.Mac/layout.sh --configuration='$(configuration)' --output='$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/payload' --symbol-output='$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/symbols' --runtime=${{ parameters.osxRuntime }}
    displayName: Layout installer payload

  - task: PublishPipelineArtifact@0
    displayName: Upload unsigned payload
    inputs:
      artifactName: 'tmp.${{ parameters.osxRuntime }}.payload_unsigned' 
      targetPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/payload'

  - task: PublishPipelineArtifact@0
    displayName: Upload symbols
    inputs:
      artifactName: 'tmp.${{ parameters.osxRuntime }}.symbols'
      targetPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/symbols'
