parameters:
- name: osxRuntime
  type: string
  default: osx-x64

steps:
  - task: DownloadPipelineArtifact@1
    displayName: Download signed installer
    inputs:
      buildType: 'current'
      artifactName: 'tmp.${{ parameters.osxRuntime }}.installer_signed'
      downloadPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/pkg'

  - task: DownloadPipelineArtifact@1
    displayName: Download signed payload
    inputs:
      buildType: 'current'
      artifactName: 'tmp.${{ parameters.osxRuntime }}.payload_signed'
      downloadPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/payload'

  - task: DownloadPipelineArtifact@1
    displayName: Download symbols
    inputs:
      buildType: 'current'
      artifactName: 'tmp.${{ parameters.osxRuntime }}.symbols'
      downloadPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/symbols'

  # Skip notarization until we can preserve the hardened runtime bit and sign the .NET runtime bits
  # Tracked: https://github.com/microsoft/Git-Credential-Manager-Core/issues/108
  #- script: src/osx/SignFiles.Mac/notarize-pkg.sh -id "$(AppleId)" -p "$(AppleIdPassword)" -pkg "$(Build.StagingDirectory)"/pkg/*.pkg
  #  displayName: Notarize and staple installer package

  - script: |
      mkdir -p "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/payload" "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/payload.sym"
      cp -f  "$(Build.StagingDirectory)"/${{ parameters.osxRuntime }}/pkg/*.pkg "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/"
      cp -Rf "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/payload/"  "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/payload/"
      cp -Rf "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/symbols/"  "$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/payload.sym/"
    displayName: Prepare final build artifacts

  - script: dotnet tool install --global nbgv
    displayName: Install Nerdbank.GitVersioning tool

  - script: nbgv cloud --common-vars
    displayName: Set version variables

  - task: ArchiveFiles@2
    displayName: Create payload archive
    inputs:
      rootFolderOrFile: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/payload/'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/gcmcore-${{ parameters.osxRuntime }}-$(GitBuildVersionSimple).tar.gz'
      replaceExistingArchive: true

  - task: ArchiveFiles@2
    displayName: Create symbol archive
    inputs:
      rootFolderOrFile: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/payload.sym/'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish/symbols-${{ parameters.osxRuntime }}.tar.gz'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@0
    displayName: Publish signed installer artifacts
    inputs:
      artifactName: 'Installer.Mac.Signed'
      targetPath: '$(Build.StagingDirectory)/${{ parameters.osxRuntime }}/publish'
